Resemble interpolate the combined weather data
Combine_S1_all_outs
Combine_S2_all_outs

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import csv 
import matplotlib.pyplot as plt
import pytz
# import siphon

In [2]:
dfs=pd.read_csv('Combine_S1_all_outs.csv',index_col=0)  
# dfs=pd.read_csv('Combine_S2_all_outs.csv',index_col=0)      

dfs.head()
# dfs.describe()

,Temperature_surface,U-component_of_wind,V-component_of_wind,Total_cloud_cover_entire_atmosphere,Total_precipitation,Snow_depth,Albedo,Downward_Short-Wave_Rad_Flux,Upward_Short-Wave_Rad_Flux_surface
2017-12-31 09:00:00+09:00,268.044037,8.190327,5.819194,97.0,0.0000,0.35,0.0,0.0,0.0
2017-12-31 12:00:00+09:00,266.276855,8.253903,5.855371,97.0,0.0000,0.34,0.0,0.0,0.0
2017-12-31 15:00:00+09:00,264.686035,8.035964,5.302947,83.0,0.0000,0.34,0.0,0.0,0.0
2017-12-31 18:00:00+09:00,267.970856,7.983994,5.279997,89.0,0.0000,0.34,0.0,0.0,0.0
2017-12-31 21:00:00+09:00,269.940857,7.946909,5.588449,99.0,0.0625,0.34,0.0,0.0,0.0

In [3]:
import os
import itertools
import matplotlib.pyplot as plt
import pandas as pd
import pvlib
from pvlib import clearsky, atmosphere, solarposition
from pvlib.location import Location

In [4]:
dfs.index

Index(['2017-12-31 09:00:00+09:00', '2017-12-31 12:00:00+09:00',
       '2017-12-31 15:00:00+09:00', '2017-12-31 18:00:00+09:00',
       '2017-12-31 21:00:00+09:00', '2018-01-01 00:00:00+09:00',
       '2018-01-01 03:00:00+09:00', '2018-01-01 06:00:00+09:00',
       '2018-01-01 09:00:00+09:00', '2018-01-01 12:00:00+09:00',
       ...
       '2019-01-29 12:00:00+09:00', '2019-01-29 15:00:00+09:00',
       '2019-01-29 18:00:00+09:00', '2019-01-29 21:00:00+09:00',
       '2019-01-30 00:00:00+09:00', '2019-01-30 03:00:00+09:00',
       '2019-01-30 06:00:00+09:00', '2019-01-30 09:00:00+09:00',
       '2019-01-30 12:00:00+09:00', '2019-01-30 15:00:00+09:00'],
      dtype='object', length=3115)

In [5]:
dfs.index=pd.to_datetime(dfs.index)
dfs.index=dfs.index.tz_localize('UTC').tz_convert('Japan')
dfs.index

DatetimeIndex(['2017-12-31 09:00:00+09:00', '2017-12-31 12:00:00+09:00',
               '2017-12-31 15:00:00+09:00', '2017-12-31 18:00:00+09:00',
               '2017-12-31 21:00:00+09:00', '2018-01-01 00:00:00+09:00',
               '2018-01-01 03:00:00+09:00', '2018-01-01 06:00:00+09:00',
               '2018-01-01 09:00:00+09:00', '2018-01-01 12:00:00+09:00',
               ...
               '2019-01-29 12:00:00+09:00', '2019-01-29 15:00:00+09:00',
               '2019-01-29 18:00:00+09:00', '2019-01-29 21:00:00+09:00',
               '2019-01-30 00:00:00+09:00', '2019-01-30 03:00:00+09:00',
               '2019-01-30 06:00:00+09:00', '2019-01-30 09:00:00+09:00',
               '2019-01-30 12:00:00+09:00', '2019-01-30 15:00:00+09:00'],
              dtype='datetime64[ns, Japan]', length=3115, freq=None)

In [6]:
# resampled_data = data.resample('5min').interpolate()
res_dfs= dfs.resample('30min').interpolate()
res_dfs.head()

,Temperature_surface,U-component_of_wind,V-component_of_wind,Total_cloud_cover_entire_atmosphere,Total_precipitation,Snow_depth,Albedo,Downward_Short-Wave_Rad_Flux,Upward_Short-Wave_Rad_Flux_surface
2017-12-31 09:00:00+09:00,268.044037,8.190327,5.819194,97.0,0.0,0.350000,0.0,0.0,0.0
2017-12-31 09:30:00+09:00,267.749507,8.200923,5.825224,97.0,0.0,0.348333,0.0,0.0,0.0
2017-12-31 10:00:00+09:00,267.454976,8.211519,5.831253,97.0,0.0,0.346667,0.0,0.0,0.0
2017-12-31 10:30:00+09:00,267.160446,8.222115,5.837283,97.0,0.0,0.345000,0.0,0.0,0.0
2017-12-31 11:00:00+09:00,266.865916,8.232711,5.843312,97.0,0.0,0.343333,0.0,0.0,0.0

In [7]:
# dfs.describe()
res_dfs.describe()

,Temperature_surface,U-component_of_wind,V-component_of_wind,Total_cloud_cover_entire_atmosphere,Total_precipitation,Snow_depth,Albedo,Downward_Short-Wave_Rad_Flux,Upward_Short-Wave_Rad_Flux_surface
count,18973.000000,18973.000000,18973.000000,18973.000000,18973.000000,18973.000000,18973.000000,18973.000000,18973.000000
mean,265.438432,1.847831,-0.014286,69.826438,0.261292,0.288409,29.565229,99.781268,45.095662
std,15.979627,4.680300,5.619447,33.914643,0.716365,0.248939,32.621882,156.597234,90.681572
min,231.049408,-10.890520,-13.481758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,252.602219,-1.343591,-4.411313,46.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,265.186824,2.253004,-0.288854,85.833333,0.020833,0.330000,14.600000,13.333333,5.333333
75%,278.007355,4.954317,4.093707,99.500000,0.177083,0.510000,71.213333,143.166667,44.000000
max,303.857605,16.959265,18.771957,100.000000,18.687500,0.790000,80.290001,740.000000,596.000000

In [8]:
# dx=pd.to_datetime('2017-12-31 06:00:00+09:00')
dx= pd.Timestamp(2017,12,31,16,0,0).tz_localize('UTC')
dx_jp=dx.tz_convert('Japan')
form_dx_jp=dx_jp.strftime('%Y-%m-%d %H:%M:%S')
print(dx)
print(dx_jp)
print(form_dx_jp)

2017-12-31 16:00:00+00:00
2018-01-01 01:00:00+09:00
2018-01-01 01:00:00

In [9]:
##### This cell is just sample data for test conversion of UTC to Japan timezone
res_dx1=pd.to_datetime(['2017-12-31 09:00:00', '2017-12-31 09:30:00', '2017-12-31 21:00:00'])
res_dx1=res_dx1.tz_localize('UTC')
res_jp1=res_dx1.tz_convert('Japan')
form_res_jp1=res_jp1.strftime('%Y-%m-%d %H:%M:%S')

print(res_dx1)
print(res_jp1)
print(form_res_jp1)

DatetimeIndex(['2017-12-31 09:00:00+00:00', '2017-12-31 09:30:00+00:00',
               '2017-12-31 21:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)
DatetimeIndex(['2017-12-31 18:00:00+09:00', '2017-12-31 18:30:00+09:00',
               '2018-01-01 06:00:00+09:00'],
              dtype='datetime64[ns, Japan]', freq=None)
Index(['2017-12-31 18:00:00', '2017-12-31 18:30:00', '2018-01-01 06:00:00'], dtype='object')

In [10]:
res_dx=pd.to_datetime(res_dfs.index.strftime('%Y-%m-%d %H:%M:%S'))
res_dx_utc=res_dx.tz_localize('UTC')
res_jp=res_dx_utc.tz_convert('Japan')
form_res_jp=res_jp.strftime('%Y-%m-%d %H:%M:%S')
# print(res_dx_utc)
# print(res_jp)
print(form_res_jp)

Index(['2017-12-31 18:00:00', '2017-12-31 18:30:00', '2017-12-31 19:00:00',
       '2017-12-31 19:30:00', '2017-12-31 20:00:00', '2017-12-31 20:30:00',
       '2017-12-31 21:00:00', '2017-12-31 21:30:00', '2017-12-31 22:00:00',
       '2017-12-31 22:30:00',
       ...
       '2019-01-30 19:30:00', '2019-01-30 20:00:00', '2019-01-30 20:30:00',
       '2019-01-30 21:00:00', '2019-01-30 21:30:00', '2019-01-30 22:00:00',
       '2019-01-30 22:30:00', '2019-01-30 23:00:00', '2019-01-30 23:30:00',
       '2019-01-31 00:00:00'],
      dtype='object', length=18973)

In case of using (...res_jp.date & res_jp.time) this will lead to the adjust the time as Japan timezone rather than UTC in case of using (...res_dfs.index.date & res_dfs.index.time)
Note:When changes occur this needs to clear and restart to run the script

In [11]:
#### res_dfs["DATE"] = res_dfs.index.date
#### res_dfs["TIME"] = res_dfs.index.time

# res_dfs.insert(0, 'DATE', res_dfs.index.date)
# res_dfs.insert(1, 'TIME', res_dfs.index.time)

res_dfs.insert(0, 'DATE', res_jp.date)
res_dfs.insert(1, 'TIME', res_jp.time)

res_dfs.head()

,DATE,TIME,Temperature_surface,U-component_of_wind,V-component_of_wind,Total_cloud_cover_entire_atmosphere,Total_precipitation,Snow_depth,Albedo,Downward_Short-Wave_Rad_Flux,Upward_Short-Wave_Rad_Flux_surface
2017-12-31 09:00:00+09:00,2017-12-31,18:00:00,268.044037,8.190327,5.819194,97.0,0.0,0.350000,0.0,0.0,0.0
2017-12-31 09:30:00+09:00,2017-12-31,18:30:00,267.749507,8.200923,5.825224,97.0,0.0,0.348333,0.0,0.0,0.0
2017-12-31 10:00:00+09:00,2017-12-31,19:00:00,267.454976,8.211519,5.831253,97.0,0.0,0.346667,0.0,0.0,0.0
2017-12-31 10:30:00+09:00,2017-12-31,19:30:00,267.160446,8.222115,5.837283,97.0,0.0,0.345000,0.0,0.0,0.0
2017-12-31 11:00:00+09:00,2017-12-31,20:00:00,266.865916,8.232711,5.843312,97.0,0.0,0.343333,0.0,0.0,0.0

In [12]:
# res_jp
res_dfs.head()

,DATE,TIME,Temperature_surface,U-component_of_wind,V-component_of_wind,Total_cloud_cover_entire_atmosphere,Total_precipitation,Snow_depth,Albedo,Downward_Short-Wave_Rad_Flux,Upward_Short-Wave_Rad_Flux_surface
2017-12-31 09:00:00+09:00,2017-12-31,18:00:00,268.044037,8.190327,5.819194,97.0,0.0,0.350000,0.0,0.0,0.0
2017-12-31 09:30:00+09:00,2017-12-31,18:30:00,267.749507,8.200923,5.825224,97.0,0.0,0.348333,0.0,0.0,0.0
2017-12-31 10:00:00+09:00,2017-12-31,19:00:00,267.454976,8.211519,5.831253,97.0,0.0,0.346667,0.0,0.0,0.0
2017-12-31 10:30:00+09:00,2017-12-31,19:30:00,267.160446,8.222115,5.837283,97.0,0.0,0.345000,0.0,0.0,0.0
2017-12-31 11:00:00+09:00,2017-12-31,20:00:00,266.865916,8.232711,5.843312,97.0,0.0,0.343333,0.0,0.0,0.0

Note: Some cells needs to run the clear and restart 

Saving the resampled data in CVS file

In [14]:
# res_dfs.to_csv('Res_comb_S1_mes_tz_Jp.csv', encoding='utf-8', index=False)
# res_dfs.to_csv('Res_comb_S2_mes_tz_Jp.csv', encoding='utf-8', index=False)